{{- if .Values.s3.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.s3.serviceAccountName }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.s3.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ .Values.s3.secretName }}
{{- end }}
